version: '3.4'

services:
  influxdb:
    image: influxdb:1.8.4
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_DB=${INFLUXDB_DB}

  grafana:
    restart: always
    image: grafana/grafana:7.5.4
    volumes:
      - ./grafana:/etc/grafana/provisioning
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
    depends_on:
      - influxdb

  speedtest:
    restart: always
    network_mode: host
    build: ./speedtest
    image: turbothinh/network-speedtest:latest
    volumes:
      - ./speedtest/src:/src
    environment:
      - CRON_CONFIG=${CRON_CONFIG}
      - SPEEDTEST_HOST=${SPEEDTEST_HOST}
      - SPEEDTEST_SERVER_ID=${SPEEDTEST_SERVER_ID}
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

    depends_on:
      - influxdb
