apiVersion: 1

deleteDatasources:
  - name: InfluxDB

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: network_speed
    user: root # Update this to your Influx User
    password: Secret123 # Update this to your Influx Password
    url: http://influxdb:8086
